
name: Shoggquah Tlachxa
description: NotDeveloper from Nowhere

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Set the Sass partials directory, as we're using @imports
#sass:
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-merlot